import { useState } from 'react'
import { useResource } from '../hooks/useResource'
import { stocks, market, funds } from '../api/services'
import Icon from '../components/Icon'
import { DataPanel, Empty, Fields, ResourceState } from '../components/DataView'
import { Heading, StockPanel, Tabs } from '../components/MarketComponents'
import { money, stockRow } from '../utils/format'
import NewsList from '../components/NewsList'
import { FeaturedChart, MarketSnapshot, QuoteStrip } from '../components/MarketOverview'

export function Dashboard({ user }) {
  const trending = useResource(market.trending), [active, setActive] = useState('nse'), [mover, setMover] = useState('top_gainers')
  const mostActive = useResource(market[active]), [range, setRange] = useState('high52Week'), highs = useResource(market.highsLows), shockers = useResource(market.shockers)
  return <><QuoteStrip resource={trending}/><Heading eyebrow="YOUR DAILY MARKET BRIEF" title="Market overview" description={`Welcome back, ${user.name.split(' ')[0]}. Find the movement that matters.`}><span className="date">{new Date().toLocaleDateString('en-IN', { timeZone: 'Asia/Kolkata', weekday: 'short', day: 'numeric', month: 'short', year: 'numeric' })}</span><a href="#/search" className="button">Discover stocks <Icon name="arrow" size={15}/></a></Heading><MarketSnapshot resource={trending}/><div className="terminal-grid"><FeaturedChart resource={trending}/><StockPanel title="Market movers" resource={trending} rows={trending.data?.trending_stocks?.[mover]} limit={6}><Tabs values={[['top_gainers', 'Gainers'], ['top_losers', 'Losers']]} selected={mover} setSelected={setMover}/></StockPanel></div><div className="grid-two"><StockPanel title="Most active" resource={mostActive} limit={5} extra="volume"><Tabs values={[['nse', 'NSE'], ['bse', 'BSE']]} selected={active} setSelected={setActive}/></StockPanel><StockPanel title="52-week range · NSE" resource={highs} rows={highs.data?.NSE_52WeekHighLow?.[range] || []} extra={range === 'high52Week' ? 'high' : 'low'} limit={5}><Tabs values={[['high52Week', 'New highs'], ['low52Week', 'New lows']]} selected={range} setSelected={setRange}/></StockPanel></div><StockPanel title="Price shockers" resource={shockers} limit={8}/></>
}
export function MarketScreen() {
  const [view, setView] = useState('trending'), [mover, setMover] = useState('top_gainers'), [exchange, setExchange] = useState('NSE'), [range, setRange] = useState('high52Week'), resource = useResource(market[view])
  const rows = view === 'trending' ? resource.data?.trending_stocks?.[mover] : view === 'highsLows' ? resource.data?.[`${exchange}_52WeekHighLow`]?.[range] : undefined
  return <><Heading title="The market, in motion." description="Follow the stocks making a move across NSE and BSE."/><Tabs className="market-tabs" values={[['trending', 'Trending stocks'], ['nse', 'NSE most active'], ['bse', 'BSE most active'], ['highsLows', '52-week highs & lows'], ['shockers', 'Price shockers']]} selected={view} setSelected={setView}/><StockPanel title={view === 'trending' ? 'Market movers' : view === 'highsLows' ? '52-week range' : view === 'shockers' ? 'Price shockers' : `${view.toUpperCase()} most active`} resource={resource} rows={rows} extra={view === 'highsLows' ? range === 'high52Week' ? 'high' : 'low' : ['nse', 'bse'].includes(view) ? 'volume' : undefined}>{view === 'trending' ? <Tabs values={[['top_gainers', 'Gainers'], ['top_losers', 'Losers']]} selected={mover} setSelected={setMover}/> : view === 'highsLows' ? <><Tabs values={[['NSE', 'NSE'], ['BSE', 'BSE']]} selected={exchange} setSelected={setExchange}/><Tabs values={[['high52Week', 'Highs'], ['low52Week', 'Lows']]} selected={range} setSelected={setRange}/></> : null}</StockPanel></>
}
export function SearchScreen({ initialQuery = '' }) {
  const [input, setInput] = useState(initialQuery), [query, setQuery] = useState(initialQuery), [type, setType] = useState('stock'), resource = useResource(query ? type === 'industry' ? stocks.industry(query) : stocks.search(query) : null)
  return <><Heading eyebrow="GO BEYOND THE HEADLINES" title="Find your next perspective." description="Look up a company, stock symbol, or industry."/><div className="search-controls"><form className="search-form" onSubmit={e => { e.preventDefault(); setQuery(input.trim()) }}><Icon name="search"/><input aria-label="Company, stock symbol, or industry" placeholder={type === 'industry' ? 'Search an industry…' : 'Try Reliance, TCS, or Infosys…'} maxLength={160} value={input} onChange={e => setInput(e.target.value)}/><button className="button" disabled={!input.trim()}>Search <Icon name="arrow" size={14}/></button></form><select value={type} onChange={e => setType(e.target.value)} aria-label="Search type"><option value="stock">Company / symbol</option><option value="industry">Industry</option></select></div>{type === 'stock' && <p className="search-hint">Company lookup returns the closest match from Indian API.</p>}<section className="panel"><div className="panel-heading"><h2>{query ? `Results for “${query}”` : 'Stock discovery'}</h2>{query && <button className="icon-button" aria-label="Refresh results" onClick={resource.retry}><Icon name="refresh" size={15}/></button>}</div>{!query ? <Empty title="Start with a name" message="Search for a company or symbol to explore its prices, financials, and history."/> : resource.error?.code === 'NO_DATA' ? <Empty title="No stocks found." message="Try a different company name or stock symbol."/> : <ResourceState resource={resource}>{Array.isArray(resource.data) && resource.data.length ? resource.data.map((value, i) => { const row = stockRow(value); return <a className="result-link" key={value.id || row.symbol || i} href={`#/stock/${encodeURIComponent(row.name || row.symbol || '')}`}><span className="company-initial">{String(row.symbol || row.name || '').slice(0, 2)}</span><div><strong>{row.name || row.symbol}</strong><p>{row.symbol}{value.mgIndustry && ` · ${value.mgIndustry}`}</p></div><Icon name="arrow" size={18}/></a> }) : <Empty title="No stocks found." message="Try another company or industry."/>}</ResourceState>}</section></>
}
export function NewsScreen() { const resource = useResource(market.news); return <><Heading eyebrow="THE STORIES BEHIND THE MARKET" title="Stay in the know." description="The latest market news, straight from Indian API."/><section className="panel"><div className="panel-heading"><h2>Market news</h2><button className="icon-button" onClick={resource.retry} aria-label="Refresh news"><Icon name="refresh" size={16}/></button></div><ResourceState resource={resource}><NewsList data={resource.data}/></ResourceState></section></> }
export function FundsScreen() {
  const [input, setInput] = useState(''), [query, setQuery] = useState(''), list = useResource(query ? funds.search(query) : funds.list)
  return <><Heading eyebrow="THINKING A LITTLE LONGER TERM" title="Explore mutual funds." description="Find a scheme and get a closer look at its available data."/><form className="search-form" style={{ marginBottom: 24 }} onSubmit={e => { e.preventDefault(); setQuery(input.trim()) }}><Icon name="search"/><input value={input} onChange={e => setInput(e.target.value)} placeholder="Search fund names, e.g. Nippon or SBI…" aria-label="Search mutual funds" maxLength={160}/><button className="button">{input.trim() ? 'Search' : 'All funds'}<Icon name="arrow" size={14}/></button></form><section className="panel"><div className="panel-heading"><h2>{query ? `Funds matching “${query}”` : 'Mutual fund landscape'}</h2>{query && <button className="text-link" onClick={() => { setQuery(''); setInput('') }} style={{ background: 'none' }}>Clear search</button>}</div><ResourceState resource={list}>{query && Array.isArray(list.data) ? list.data.length ? list.data.map((fund, i) => <a key={fund.id || i} className="result-link" href={`#/fund/${encodeURIComponent(fund.schemeName || '')}`}><span className="company-initial"><Icon name="fund" size={17}/></span><div><strong>{fund.schemeName}</strong><p>{fund.schemeType}{fund.isin && ` · ${fund.isin}`}</p></div><Icon name="arrow" size={17}/></a>) : <Empty title="No funds found" message="Try a different scheme or fund house."/> : <FundLandscape data={list.data}/>}</ResourceState></section></>
}
function FundLandscape({ data, depth = 0 }) {
  if (Array.isArray(data)) return data.length ? data.map((fund, i) => fund && typeof fund === 'object' && typeof fund.fund_name === 'string' ? <div key={i}><a className="result-link" href={`#/fund/${encodeURIComponent(fund.fund_name)}`}><span className="company-initial"><Icon name="fund" size={16}/></span><div><strong>{fund.fund_name}</strong>{fund.latest_nav != null && <p>NAV {money(fund.latest_nav)}</p>}</div><Icon name="arrow" size={17}/></a><details className="data-detail"><summary>Available fund metrics</summary><Fields data={fund}/></details></div> : <Fields data={fund} key={i}/>) : <Empty/>
  if (!data || typeof data !== 'object' || !Object.keys(data).length) return <Empty/>
  if (depth > 4) return <Fields data={data}/>
  return Object.entries(data).map(([key, value]) => <details className="data-detail" key={key} open={depth === 0}><summary>{key}</summary><FundLandscape data={value} depth={depth + 1}/></details>)
}
export function FundDetails({ name }) { const resource = useResource(funds.details(name)); return <><a href="#/funds" className="back-link"><Icon name="back" size={15}/>Back to mutual funds</a><Heading eyebrow="MUTUAL FUND DETAILS" title={name} description="Scheme information as returned by Indian API."/><DataPanel title="Scheme overview" resource={resource}/></> }
export function SimpleScreen({ type }) { const resource = useResource(market[type]); return <><Heading eyebrow={type === 'ipo' ? 'WHAT’S COMING TO MARKET' : 'BEYOND EQUITIES'} title={type === 'ipo' ? 'The IPO landscape.' : 'Commodities, in focus.'} description={type === 'ipo' ? 'Explore the IPO information available from Indian API.' : 'Follow available commodity contracts, prices, and activity.'}/><DataPanel title={type === 'ipo' ? 'IPO information' : 'Commodity contracts'} resource={resource}/></> }
