import { useState } from 'react'
import { useResource } from '../hooks/useResource'
import { stocks } from '../api/services'
import Icon from '../components/Icon'
import { DataPanel, Fields, ResourceState } from '../components/DataView'
import { Change, Tabs } from '../components/MarketComponents'
import { money } from '../utils/format'
import HistoryChart from '../components/HistoryChart'
import NewsList from '../components/NewsList'
export default function StockDetails({ name }) {
  const resource = useResource(stocks.details(name)), [period, setPeriod] = useState('1yr'), [tab, setTab] = useState('overview'), history = useResource(stocks.history(name, period)), data = resource.data
  return <><a className="back-link" href="#/search"><Icon name="back" size={15}/>Back to stock discovery</a><section className="panel"><ResourceState resource={resource}>{data && <><div className="stock-detail-heading"><div><span className="eyebrow">{data.industry || 'COMPANY OVERVIEW'}</span><h1>{data.companyName}</h1>{data.tickerId && <p>{data.tickerId}{data.currentPrice?.NSE != null ? ' · NSE' : data.currentPrice?.BSE != null ? ' · BSE' : ''}</p>}</div><div className="price-block"><strong>{money(data.currentPrice?.NSE ?? data.currentPrice?.BSE)}</strong>{data.percentChange != null && <Change value={data.percentChange}/>}</div></div><div className="metrics">{Object.entries({ '52-week high': data.yearHigh, '52-week low': data.yearLow, 'NSE price': data.currentPrice?.NSE, 'BSE price': data.currentPrice?.BSE }).filter(([, value]) => value != null).map(([key, value]) => <div key={key} className="metric"><small>{key}</small><b>{money(value)}</b></div>)}</div></>}</ResourceState></section><section className="panel"><div className="panel-heading"><div><h2>Price history</h2><p>Prices and dates as returned by Indian API</p></div><select className="select-control" aria-label="Historical period" value={period} onChange={e => setPeriod(e.target.value)}>{[['1m', '1 month'], ['6m', '6 months'], ['1yr', '1 year'], ['3yr', '3 years'], ['5yr', '5 years'], ['10yr', '10 years'], ['max', 'All time']].map(([v, l]) => <option value={v} key={v}>{l}</option>)}</select></div><ResourceState resource={history}><HistoryChart data={history.data}/></ResourceState></section><Tabs className="market-tabs" values={[['overview', 'Company'], ['financials', 'Financials'], ['technical', 'Technical'], ['analysts', 'Analysts'], ['shareholding', 'Shareholding'], ['actions', 'Corporate actions'], ['news', 'Company news']]} selected={tab} setSelected={setTab}/>{tab === 'actions' ? <CorporateActions name={name}/> : tab === 'financials' ? <Financials name={name} data={data}/> : tab === 'analysts' ? <Analysts data={data}/> : <section className="panel"><div className="panel-heading"><h2>{tab === 'overview' ? 'About the company' : tab === 'technical' ? 'Technical information' : tab === 'shareholding' ? 'Shareholding information' : 'Recent news'}</h2></div><ResourceState resource={resource}>{tab === 'news' ? <NewsList data={data?.recentNews || []}/> : <Fields data={data?.[tab === 'overview' ? 'companyProfile' : tab === 'technical' ? 'stockTechnicalData' : 'shareholding'] || {}}/>}</ResourceState></section>}</>
}
function CorporateActions({ name }) { const actions = useResource(stocks.actions(name)), announcements = useResource(stocks.announcements(name)); return <div className="grid-two"><DataPanel title="Corporate actions" resource={actions}/><DataPanel title="Recent announcements" resource={announcements}/></div> }
function Financials({ name, data }) {
  const [stat, setStat] = useState('quarter_results'), stats = useResource(stocks.stats(name, stat))
  return <><section className="panel"><div className="panel-heading"><h2>Key metrics</h2></div><Fields data={data?.keyMetrics || {}}/></section><section className="panel"><div className="panel-heading"><h2>Historical financials</h2><select className="select-control" aria-label="Financial statement" value={stat} onChange={e => setStat(e.target.value)}>{['quarter_results', 'yoy_results', 'balancesheet', 'cashflow', 'ratios', 'shareholding_pattern_quarterly', 'shareholding_pattern_yearly'].map(v => <option key={v} value={v}>{v.replaceAll('_', ' ')}</option>)}</select></div><ResourceState resource={stats}><Fields data={stats.data}/></ResourceState></section>{data?.financials && <section className="panel"><div className="panel-heading"><h2>Financial information</h2></div><Fields data={data.financials}/></section>}</>
}
function Analysts({ data }) { return <section className="panel"><div className="panel-heading"><h2>Analyst information</h2></div><Fields data={Object.fromEntries(['analystView', 'recosBar', 'riskMeter'].filter(key => data?.[key] != null).map(key => [key, data[key]]))}/></section> }
